# Generated by Django 4.1.6 on 2023-02-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='users.location'),
        ),
    ]
